version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    command: npm start

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:8080"
    depends_on:
      - app
