version: "3.8"
services:
  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  node-service:
    build:
      context: ./docker/api
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    depends_on:
      - db

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - node-service
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/docker/nginx/nginx.conf

volumes:
  db-data:
